routes/web.php
<?php

Route::get('/', function () {
    return view('index');
});

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

Auth::routes();

Route::middleware(['auth', 'workspace'])->group(function () {
    Route::resource('document/initialize', '\App\Http\Controllers\Document\InitializeController', ['only' => ['create', 'store']]);
    Route::resource('document/version', '\App\Http\Controllers\Document\VersionController', ['only' => ['edit', 'update']]);
    Route::resource('document/sign', '\App\Http\Controllers\Document\SignController', ['only' => ['index', 'edit', 'update']]);
    Route::resource('document/notification', '\App\Http\Controllers\Document\NotificationController', ['only' => ['index', 'edit', 'update']]);
    Route::resource('document', 'DocumentController');
    Route::resource('device', 'DeviceController');
    Route::resource('device/initialize', '\App\Http\Controllers\Device\InitializeController', ['as' => 'device', 'only' => ['create', 'store']]);
    Route::resource('workspace', 'WorkspaceController', ['only' => ['index', 'update']]);
});

app/Document.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class Document extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['category_id', 'workspace_id', 'name', 'type', 'based_on_version', 'based_on', 'notify'];

//    /**
//     * The relations to eager load on every query.
//     *
//     * @var array
//     */
//    protected $with = ['documentFiles'];

    /********** Override **********/
    /**
     * Fill the model with an array of attributes.
     *
     * @param  array  $attributes
     * @return $this
     *
     * @throws \Illuminate\Database\Eloquent\MassAssignmentException
     */
    public function fill(array $attributes)
    {
        if (Auth::user()->workspace && !isset($attributes['workspace_id'])) {
            $attributes['workspace_id'] = Auth::user()->workspace->id;
        }
        return parent::fill($attributes);
    }
    /********** Override **********/

    /********** Voyager relations **********/
    /**
     * @return \Illuminate\Database\Eloquent\Relations\belongsTo
     */
    public function workspaceId()
    {
        return $this->belongsTo(\App\Workspace::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\belongsTo
     */
    public function categoryId()
    {
        return $this->belongsTo(\App\Category::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function basedOn()
    {
        return $this->hasOne(\App\Document::class, 'id', 'based_on');
    }
    /********** Voyager relations **********/

    /********** Relations **********/
    /**
     * @return \Illuminate\Database\Eloquent\Relations\hasMany
     */
    public function documentFiles()
    {
        return $this->hasMany(\App\DocumentFile::class);
    }
    public function documentfile()
    {
        return $this->documentFiles();
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\hasMany
     */
    public function signedDocumentFiles()
    {
        return $this->hasMany(\App\DocumentFile::class)->where('signed', '>', 0)->whereIn('type', config('document.signable'));
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\hasMany
     */
    public function pendingDocumentFiles()
    {
        return $this->hasMany(\App\DocumentFile::class)->where('signed', null)->whereIn('type', config('document.signable'));
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\belongsTo
     */
    public function workspace()
    {
        return $this->workspaceId();
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\belongsTo
     */
    public function category()
    {
        return $this->categoryId();
    }
    /********** Relations **********/

    /********** Clone **********/
    public function clone() {
        $documentFile = $this->newest_document_file;

        $clone = $this->replicate();
        $clone->workspace_id = Auth::user()->workspace->id;
        $clone->based_on = $this->id;
        $clone->save();

        $cloneFile = $documentFile->replicate();
        $cloneFile->document_id = $clone->id;
        unset($cloneFile->signed, $cloneFile->signature);

        if ($documentFile->hasMedia('file')) {
            $cloneFile->copyMedia($documentFile->getFirstMedia('file')->getPath())->toMediaCollection('file');
        }

        $cloneFile->save();
    }
    /********** Clone **********/

    /********** Signable **********/
    public function getSignableAttribute($value = '')
    {
        return $this->generator->signable();
    }
    public function getNewestDocumentFileAttribute($value = '')
    {
        if (Auth::user()->hasPermission('edit_documents')) {
            return $this->documentFiles->sortByDesc('version')->first();
        }
        return $this->newest_signed_document_file;
    }
    public function getNewestSignedDocumentFileAttribute($value = '')
    {
        return $this->signable ? $this->documentFiles->sortByDesc('version')->filter->signed->first() : null;
    }
    /********** Signable **********/

    /********** Edit / Version / Pending Button **********/
    public function getEditVersionAttribute($value = '')
    {
        return optional($this->newest_document_file)->signed && $this->signable;
    }
    public function getEditVersionUrlAttribute($value = '')
    {
        if (request()->route()->named('sign.index')) {
            return route('sign.edit', $this->id);
        } elseif (request()->route()->named('notification.index')) {
            return route('notification.edit', $this->id);
        }
        return $this->edit_version ? route('version.edit', $this->id) : route('document.edit', $this->id);
    }
    public function getEditVersionIconAttribute($value = '')
    {
        return $this->edit_version ? 'fa fa-files-o' : 'fa fa-edit';
    }
    /********** Edit / Version / Pending Button **********/

    /********** View Button **********/
    public function getViewUrlAttribute($value = '')
    {
        return route('document.show', $this->id);
    }
    public function getViewIconAttribute($value = '')
    {
        return $this->generator->icon();
    }
    /********** View Button **********/

    /********** Generator **********/
    public function getGeneratorAttribute($value = '') {
        return class_exists($this->type) ? optional(new $this->type($this)) : optional(null);
    }
    /********** Generator **********/

    /********** Download Log **********/
    public function logged()
    {
        if (Auth::user()->hasPermission('edit_documents')) return;

        return $this->newest_document_file->downloadLogs()->create(['user_id' => Auth::user()->id]);
    }
    /********** Download Log **********/

    /********** Mutators **********/

    /********** Signable **********/
    public function setNotifyAttribute($value)
    {
        $this->attributes['notify'] = boolval($value);
    }
    /********** Mutators **********/
}

app/DocumentFile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMedia;

class DocumentFile extends Model implements HasMedia
{
    use HasMediaTrait;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'documentfile';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['version', 'content', 'additional_content'];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['signed'];

    /********** Voyager relations **********/
    /**
     * @return \Illuminate\Database\Eloquent\Relations\belongsTo
     */
    public function documentId()
    {
        return $this->belongsTo(\App\Document::class);
    }
    /********** Voyager relations **********/

    /********** Relations **********/
    /**
     * @return \Illuminate\Database\Eloquent\Relations\hasMany
     */
    public function downloadLogs()
    {
        return $this->hasMany(\App\DownloadLog::class, 'document_id');
    }
    /********** Relations **********/

    /********** Download Log **********/
    public function getIsNewAttribute()
    {
        return !$this->downloadLogs()->count() && $this->signed && !Auth::user()->hasPermission('edit_documents');
    }
    /********** Download Log **********/
}

app/Http/Controllers/Document/InitializeController.php
<?php

namespace App\Http\Controllers\Document;

use App\Workspace;
use Illuminate\Support\Facades\Auth;

class InitializeController
{
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        Workspace::where('master', true)->first()->documents->load('documentFiles')->each->clone();

        $workspace = Auth::user()->workspace;
        $workspace->initialized = true;
        $workspace->save();

        \App\Generator\Document\Hygieneplan::create($workspace);
        \App\Generator\Document\QMHandbuch::create($workspace, \App\Generator\Document\Organigramm::create($workspace));

        return redirect(route('document.index'));
    }
}

app/Http/Controllers/Document/NotificationController.php
<?php

namespace App\Http\Controllers\Document;

use App\Document;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class NotificationController extends \App\Http\Controllers\DocumentController
{
    /**
     * Display a listing of the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $documents = Auth::user()->workspace->documents()->with('documentFiles')->where('notify', true);

        return view('document.index', ['documents' => $documents->paginate(config('document.pagination'))]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Document $notification
     * @return \Illuminate\Http\Response
     */
    public function edit(Document $notification)
    {
        return view('document.notification.edit')->withDocument($notification->load('basedOn'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Document $notification
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Document $notification)
    {
        if ($request->clone) {
            $notification->fill($notification->basedOn->only('name', 'based_on_version'));
            $documentFile = $notification->newest_document_file->fill($notification->basedOn->newest_document_file->only('content', 'additional_content', 'signed', 'signature'));

            if ($notification->basedOn->newest_document_file->hasMedia('file')) {
                $documentFile->clearMediaCollection('file');
                $documentFile->copyMedia($notification->basedOn->newest_document_file->getFirstMedia('file')->getPath())->toMediaCollection('file');
            }
        } else {
            $notification->fill($request->all());
            $documentFile = $notification->newest_document_file->fill($request->all());
        }
        $notification->notify = false;

        $notification->save();
        $documentFile->save();

        return redirect(route('notification.index'));
    }

}

app/Http/Controllers/Document/SignController.php
<?php

namespace App\Http\Controllers\Document;

use App\Document;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class SignController extends \App\Http\Controllers\DocumentController
{
    /**
     * Display a listing of the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $documents = Auth::user()->workspace->documents()->with('documentFiles')->has('pendingDocumentFiles');

        return view('document.index', ['documents' => $documents->paginate(config('document.pagination'))]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Document $sign
     * @return \Illuminate\Http\Response
     */
    public function edit(Document $sign)
    {
        return view('document.sign.edit')->withDocument($sign);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Document $sign
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Document $sign)
    {
        $request->validate([
            'sign' => 'required|numeric|min:1'
        ]);

        $signatures = Auth::user()->workspace->signature->where('id', $request->sign);
        $signature = $signatures->first();

        $documentFile = $sign->newest_document_file;
        $documentFile->signed = new \DateTime();
        $documentFile->signature_index = $signatures->keys()->first();
        $documentFile->signature = $signature->name;
        if ($signature->hasMedia('signature')) {
            $documentFile->copyMedia($signature->getFirstMedia('signature')->getPath())->toMediaCollection('signature');
        }

        $documentFile->save();

        return redirect(route('sign.index'));
    }

}

app/Http/Controllers/Document/VersionController.php
<?php

namespace App\Http\Controllers\Document;

use App\Document;
use Illuminate\Http\Request;

class VersionController
{
    /**
     * Show the form for editing the specified resource.
     *
     * @param  Document $version
     * @return \Illuminate\Http\Response
     */
    public function edit(Document $version)
    {
        return view('document.version.edit')->withDocument($version);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Document $version
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Document $version)
    {
        $request->validate($version->generator->rules());

        $version->fill($request->all());
        if ($version->based_on) {
            $version->based_on_version = $version->based_on->newest_document_file->version;
        }

        $originalDocumentFile = $version->newest_document_file;
        $documentFile = $originalDocumentFile->fill($request->all())->replicate();
        $documentFile->version++;
        unset($documentFile->signed, $documentFile->signature);

        $version->save();
        $documentFile->save();

        Document::where('based_on', $version->id)->update(['notify' => true]);

        return redirect(route('document.index', ['category' => $version->category_id]));
    }
}

resources/views/document/categories.blade.php
@if(!isset($categories))
    @php
        $categories = \App\Category::where('parent_id', null)->get();
        $class = 'list-group-root';
    @endphp
@endif

<div class="{{ $class }}" @if (isset($id)) id="item-{{ $id }}" @endif>
    @foreach($categories as $category)
        @if ($category->subCategories->count())
            @php
                $subCategory = in_array(request()->category, $category->subCategoriesIds());
            @endphp
            <span class="list-group-item @if ($category->id == request()->category) active @endif">
                <a href="#item-{{ $category->id }}" data-toggle="collapse" class="{{ $subCategory ? '' : 'collapsed' }}">
                    <i href="#item-{{ $category->id }}" class="glyphicon glyphicon-plus"></i>
                </a>
                <a href="{{ route('document.index', ['category' => $category->id]) }}" style="width: 90%;">
                    {{ $category->name }}
                </a>
                @include('document.categories', ['categories' => $category->subCategories, 'id' => $category->id, 'class' => 'collapse' . ($subCategory ? ' in' : '')])
            </span>
        @else
            <a href="{{ route('document.index', ['category' => $category->id]) }}" class="list-group-item @if ($category->id == request()->category) active @endif">
                {{ $category->name }}
            </a>
        @endif
    @endforeach
</div>

resources/views/document/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">{{ __('document.new_document') }}</div>
                    <div class="panel-body">
                        <form class="form-horizontal" method="POST" action="{{ route('document.store') }}" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            <input type="hidden" name="type" value="{{ request()->type }}">
                            <input type="hidden" name="category_id" value="{{ request()->category }}">

                            @include('partials.textfield', ['field' => 'name', 'label' => __('document.name'), 'required' => true])

                            @switch(request()->type)
                                @case(\App\Generator\Html::class)
                                    @include('partials.richtext', ['field' => 'content', 'label' => __('document.content'), 'required' => true])
                                @break
                                @case(\App\Generator\File::class)
                                    @include('partials.file', ['field' => 'file', 'label' => __('document.file'), 'required' => true])
                                @break
                                @case(\App\Generator\Link::class)
                                    @include('partials.textfield', ['field' => 'content', 'label' => __('document.link'), 'required' => true])
                                @break
                                @default
                                    @include('partials.textarea', ['field' => 'content', 'label' => __('document.content'), 'required' => true])
                            @endswitch

                            @include('partials.submitfield', ['label' => __('document.submit')])
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/document/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">{{ __('document.edit_document') }}</div>
                    <div class="panel-body">
                        <form class="form-horizontal" method="POST" action="{{ route('document.update', $document->id) }}" enctype="multipart/form-data">
                            {{ method_field('put') }}
                            {{ csrf_field() }}

                            @include('partials.textfield', ['field' => 'name', 'label' => __('document.name'), 'required' => true, 'value' => $document->name])

                            @switch($document->type)
                                @case(\App\Generator\File::class)
                                @case(\App\Generator\Document\Organigramm::class)
                                @case(\App\Generator\Document\QMHandbuch::class)
                                    @include('document.show.file')
                                @break
                                @case(\App\Generator\Link::class)
                                    @include('partials.textfield', ['field' => 'content', 'label' => __('document.link'), 'required' => true, 'value' => optional($document->newest_document_file)->content])
                                @break
                                @default
                                    @include('partials.richtext', ['field' => 'content', 'label' => __('document.content'), 'required' => true, 'value' => optional($document->newest_document_file)->content, 'attributes' => 'readonly="readonly"'])
                            @endswitch

                            @include('partials.submitfield', ['label' => __('document.submit')])
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/document/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-4">
            @if (request()->route()->named('document.index'))
                <div class="panel panel-default">
                    <div class="panel-heading">{{ __('document.categories') }}</div>
                    <div class="panel-body">
                        @include('document.categories')
                    </div>
                </div>
            @endif
            <div class="panel panel-default">
                <div class="panel-heading">{{ __('document.links') }}</div>
                <div class="panel-body">
                    <div class="list-group-root">
                        <a href="{{ route('document.index') }}" class="list-group-item @if (request()->route()->named('document.index')) active @endif">
                            {{ __('document.document') }}
                        </a>
                        @if(Auth::user()->hasPermission('edit_documents'))
                            <a href="{{ route('sign.index') }}" class="list-group-item @if(request()->route()->named('sign.index')) active @endif">
                                {{ __('document.pending_documents') }}
                            </a>
                            <a href="{{ route('notification.index') }}" class="list-group-item @if(request()->route()->named('notification.index')) active @endif">
                                {{ __('document.notification_documents') }}
                            </a>
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="panel panel-default">
                <div class="panel-heading">{{ __('document.document') }}</div>
                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    @if (request()->category && Auth::user()->hasPermission('edit_documents'))
                        <div class="btn-group btn-group-justified">
                            <a href="{{ route('document.create', ['type' => \App\Generator\Html::class, 'category' => request()->category]) }}" class="btn btn-default">{{ __('document.new.html') }}</a>
                            <a href="{{ route('document.create', ['type' => \App\Generator\File::class, 'category' => request()->category]) }}" class="btn btn-default">{{ __('document.new.file') }}</a>
                            <a href="{{ route('document.create', ['type' => \App\Generator\Link::class, 'category' => request()->category]) }}" class="btn btn-default">{{ __('document.new.link') }}</a>
                        </div>
                        <hr>
                    @endif

                    @if ($documents->count())
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <td>{{ __('document.name') }}</td>
                                        <td>{{ __('document.version') }}</td>
                                        @if(Auth::user()->hasPermission('edit_documents'))
                                            <td></td>
                                        @endif
                                        @if (request()->route()->named('document.index'))
                                            <td></td>
                                        @endif
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($documents as $document)
                                        <tr>
                                            <td>{{ $document->name }}</td>
                                            <td>{{ optional($document->newest_document_file)->version }}</td>
                                            @if(Auth::user()->hasPermission('edit_documents'))
                                                <td align="center" style="font-size: 2rem;">
                                                    <a href="{{ $document->edit_version_url }}">
                                                        <span class="{{ $document->edit_version_icon }}"></span>
                                                    </a>
                                                </td>
                                            @endif
                                            @if (request()->route()->named('document.index'))
                                                <td align="center" style="font-size: 2rem;">
                                                    <a href="{{ $document->view_url }}" class="{{ $document->newest_document_file->is_new ? 'text-danger' : '' }}">
                                                        <span class="{{ $document->view_icon }}"></span>
                                                    </a>
                                                </td>
                                            @endif
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        {{ $documents->appends(request()->input())->links() }}
                    @else
                        <p>{{ __('document.no_documents_category') }}</p>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection