routes/web.php
<?php

Route::get('/', function () {
    return view('index');
});

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

Auth::routes();

Route::middleware(['auth', 'workspace'])->group(function () {
    Route::resource('document/initialize', '\App\Http\Controllers\Document\InitializeController', ['only' => ['create', 'store']]);
    Route::resource('document/version', '\App\Http\Controllers\Document\VersionController', ['only' => ['edit', 'update']]);
    Route::resource('document/sign', '\App\Http\Controllers\Document\SignController', ['only' => ['index', 'edit', 'update']]);
    Route::resource('document/notification', '\App\Http\Controllers\Document\NotificationController', ['only' => ['index', 'edit', 'update']]);
    Route::resource('document', 'DocumentController');
    Route::resource('device', 'DeviceController');
    Route::resource('device/initialize', '\App\Http\Controllers\Device\InitializeController', ['as' => 'device', 'only' => ['create', 'store']]);
    Route::resource('workspace', 'WorkspaceController', ['only' => ['index', 'update']]);
});

app/Workspace.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Workspace extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'workspace';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name','street','zip','city','land','terms','master','dental_assistant','medical_officers','medical_device','security_officers','laser_protection','leading_zfa','leading_zfa_representative','zfas','zfas_representative','reception','reception_representation','accounting','billing_representative','practice_laboratory','practice_laboratory_representative','staff','personal_representation','financial_accounting','financial_accounting_representative','purchase','shopping_representation','it_organization','it_organization_representative'];

    /********** Service **********/
    /**
     * @return \Illuminate\Database\Eloquent\Relations\MorphToMany
     **/
    public function contract()
    {
        return $this->morphToMany(\App\Contract::class, 'service', 'services', 'service_id', 'contract_id');
    }
    /********** Service **********/

    /********** Users **********/
    /**
     * @return \Illuminate\Database\Eloquent\Relations\MorphToMany
     */
    public function users()
    {
        return $this->morphToMany(\App\User::class, 'user_service', 'user_services', 'user_service_id', 'user_id');
    }
    /********** Users **********/

    /********** Documents **********/
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function documents()
    {
        return $this->hasMany(\App\Document::class);
    }
    /********** Documents **********/

    /********** Signature **********/
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function signature()
    {
        return $this->hasMany(\App\Signature::class);
    }
    /********** Signature **********/

    /********** Devices **********/
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function devices()
    {
        return $this->hasMany(\App\Device::class);
    }
    /********** Devices **********/

    public function setTermsAttribute($value)
    {
        $this->attributes['terms'] = boolval($value) ?: false;
    }
    public function setMasterAttribute($value)
    {
        $this->attributes['master'] = boolval($value) ?: false;
    }

    /********** Voyager BREAD **********/
    /**
     * @param array $data
     * @return mixed
     */
    public function save_users($data)
    {
        return $this->users()->sync($data);
    }
    /********** Voyager BREAD **********/
}

app/Http/Controllers/WorkspaceController.php
<?php

namespace App\Http\Controllers;

use App\Workspace;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class WorkspaceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('workspace.index')->withWorkspace(Auth::user()->workspace->load(['signature']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Workspace $workspace
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Workspace $workspace)
    {
        $workspace->load(['signature']);

        $data = $request->validate([
            'name' => 'required|string|max:255',
            'terms' => 'required|accepted',
            'dental_assistant' => 'sometimes',
            'medical_officers' => 'required',
            'medical_device' => 'required',
            'security_officers' => 'required',
            'laser_protection' => 'required',
            'leading_zfa' => 'required',
            'leading_zfa_representative' => 'sometimes',
            'zfas' => 'sometimes',
            'zfas_representative' => 'sometimes',
            'reception' => 'sometimes',
            'reception_representation' => 'sometimes',
            'accounting' => 'sometimes',
            'billing_representative' => 'sometimes',
            'practice_laboratory' => 'sometimes',
            'practice_laboratory_representative' => 'sometimes',
            'staff' => 'sometimes',
            'personal_representation' => 'sometimes',
            'financial_accounting' => 'sometimes',
            'financial_accounting_representative' => 'sometimes',
            'purchase' => 'sometimes',
            'shopping_representation' => 'sometimes',
            'it_organization' => 'sometimes',
            'it_organization_representative' => 'sometimes',
            'street' => 'required|string|max:255',
            'zip' => 'required|string|max:255',
            'city' => 'required|string|max:255',
            'land' => 'required|string|max:255',
            'signature.*.name' => 'required|string|max:255',
            'signature.*.representation' => 'sometimes',
            'signature.*.function_option' => 'sometimes',
            'signature.*.file' => 'sometimes|image',
        ]);

        $workspace->fill($data);

        if ($workspace->signature->count()) {
            foreach ($workspace->signature as $key => &$signature) {
                $signature->fill($data['signature'][$key]);
            }
        } else {
            $workspace->signature()->createMany($data['signature']);
        }

        if ($request->hasFile('signature.*.file')) {
            foreach ($workspace->signature as $key => $signature) {
                if ($request->hasFile("signature.$key.file")) {
                    if ($signature->hasMedia('signature')) {
                        $signature->clearMediaCollection('signature');
                    }
                    $signature->addMedia($request->file("signature.$key.file"))->toMediaCollection('signature');
                }
            }
        }

        if ($workspace->isDirty('terms')) {
            \App\TermsLog::logged();
        }

        $workspace->push();

        if ($workspace->initialized || $workspace->master) {
            \App\Generator\Document\Hygieneplan::create($workspace);
            \App\Generator\Document\QMHandbuch::create($workspace, \App\Generator\Document\Organigramm::create($workspace));
        }

        return redirect(route('workspace.index'));
    }
}

resources/views/workspace/index.blade.php
@extends('layouts.app')

@section('content')
    @php
        if (!old()) request()->session()->flashInput($workspace->toArray());
    @endphp

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">{{ __('document.edit_document') }}</div>
                    <div class="panel-body">
                        @if (session('status'))
                            <div class="alert alert-danger">
                                {{ session('status') }}
                            </div>
                        @endif
                        <form class="form-horizontal" method="POST" action="{{ route('workspace.update', $workspace->id) }}" enctype="multipart/form-data">
                            {{ method_field('put') }}
                            {{ csrf_field() }}

                            @include('partials.textfield', ['field' => 'name', 'label' => __('document.name'), 'required' => true])

                            @include('partials.textfield', ['field' => 'street', 'label' => __('address.street'), 'required' => true])
                            @include('partials.textfield', ['field' => 'zip', 'label' => __('address.zip'), 'required' => true])
                            @include('partials.textfield', ['field' => 'city', 'label' => __('address.city'), 'required' => true])
                            @include('partials.textfield', ['field' => 'land', 'label' => __('address.land'), 'required' => false])

                            <hr>

                            @include('partials.textfield', ['field' => 'signature[0][name]', 'label' => __('signature.0.name'), 'required' => true])
                            @include('partials.textfield', ['field' => 'signature[0][representation]', 'label' => __('signature.0.representation'), 'required' => false])
                            @include('partials.textfield', ['field' => 'signature[0][function_option]', 'label' => __('signature.0.function_option'), 'required' => false])
                            @include('partials.file', ['field' => 'signature[0][file]', 'label' => __('signature.0.file'), 'required' => false])
                            @if(isset($workspace->signature[0]) && $workspace->signature[0]->hasMedia('signature'))
                                <div class="form-group">
                                    <div class="col-md-offset-4 col-md-6">
                                        <img src="{{ $workspace->signature[0]->getFirstMedia('signature')->getUrl() }}" width="100">
                                    </div>
                                </div>
                            @endif

                            <hr>

                            @include('partials.textfield', ['field' => 'signature[1][name]', 'label' => __('signature.1.name'), 'required' => true])
                            @include('partials.textfield', ['field' => 'signature[1][representation]', 'label' => __('signature.1.representation'), 'required' => false])
                            @include('partials.textfield', ['field' => 'signature[1][function_option]', 'label' => __('signature.1.function_option'), 'required' => false])
                            @include('partials.file', ['field' => 'signature[1][file]', 'label' => __('signature.1.file'), 'required' => false])
                            @if(isset($workspace->signature[1]) && $workspace->signature[1]->hasMedia('signature'))
                                <div class="form-group">
                                    <div class="col-md-offset-4 col-md-6">
                                        <img src="{{ $workspace->signature[1]->getFirstMedia('signature')->getUrl() }}" width="100">
                                    </div>
                                </div>
                            @endif

                            <hr>

                            @include('partials.textfield', ['field' => 'signature[2][name]', 'label' => __('signature.2.name'), 'required' => true])
                            @include('partials.textfield', ['field' => 'signature[2][representation]', 'label' => __('signature.2.representation'), 'required' => false])
                            @include('partials.textfield', ['field' => 'signature[2][function_option]', 'label' => __('signature.2.function_option'), 'required' => false])
                            @include('partials.file', ['field' => 'signature[2][file]', 'label' => __('signature.2.file'), 'required' => false])
                            @if(isset($workspace->signature[2]) && $workspace->signature[2]->hasMedia('signature'))
                                <div class="form-group">
                                    <div class="col-md-offset-4 col-md-6">
                                        <img src="{{ $workspace->signature[2]->getFirstMedia('signature')->getUrl() }}" width="100">
                                    </div>
                                </div>
                            @endif

                            <hr>

                            @include('partials.textfield', ['field' => 'dental_assistant', 'label' => __('workspace.dental_assistant'), 'required' => false])
                            @include('partials.textfield', ['field' => 'medical_officers', 'label' => __('workspace.medical_officers'), 'required' => true])
                            @include('partials.textfield', ['field' => 'medical_device', 'label' => __('workspace.medical_device'), 'required' => true])
                            @include('partials.textfield', ['field' => 'security_officers', 'label' => __('workspace.security_officers'), 'required' => true])
                            @include('partials.textfield', ['field' => 'laser_protection', 'label' => __('workspace.laser_protection'), 'required' => true])
                            @include('partials.textfield', ['field' => 'leading_zfa', 'label' => __('workspace.leading_zfa'), 'required' => true])
                            @include('partials.textfield', ['field' => 'leading_zfa_representative', 'label' => __('workspace.leading_zfa_representative'), 'required' => false])
                            @include('partials.textfield', ['field' => 'zfas', 'label' => __('workspace.zfas'), 'required' => false])
                            @include('partials.textfield', ['field' => 'zfas_representative', 'label' => __('workspace.zfas_representative'), 'required' => false])
                            @include('partials.textfield', ['field' => 'reception', 'label' => __('workspace.reception'), 'required' => false])
                            @include('partials.textfield', ['field' => 'reception_representation', 'label' => __('workspace.reception_representation'), 'required' => false])
                            @include('partials.textfield', ['field' => 'accounting', 'label' => __('workspace.accounting'), 'required' => false])
                            @include('partials.textfield', ['field' => 'billing_representative', 'label' => __('workspace.billing_representative'), 'required' => false])
                            @include('partials.textfield', ['field' => 'practice_laboratory', 'label' => __('workspace.practice_laboratory'), 'required' => false])
                            @include('partials.textfield', ['field' => 'practice_laboratory_representative', 'label' => __('workspace.practice_laboratory_representative'), 'required' => false])
                            @include('partials.textfield', ['field' => 'staff', 'label' => __('workspace.staff'), 'required' => false])
                            @include('partials.textfield', ['field' => 'personal_representation', 'label' => __('workspace.personal_representation'), 'required' => false])
                            @include('partials.textfield', ['field' => 'financial_accounting', 'label' => __('workspace.financial_accounting'), 'required' => false])
                            @include('partials.textfield', ['field' => 'financial_accounting_representative', 'label' => __('workspace.financial_accounting_representative'), 'required' => false])
                            @include('partials.textfield', ['field' => 'purchase', 'label' => __('workspace.purchase'), 'required' => false])
                            @include('partials.textfield', ['field' => 'shopping_representation', 'label' => __('workspace.shopping_representation'), 'required' => false])
                            @include('partials.textfield', ['field' => 'it_organization', 'label' => __('workspace.it_organization'), 'required' => false])
                            @include('partials.textfield', ['field' => 'it_organization_representative', 'label' => __('workspace.it_organization_representative'), 'required' => false])

                            @include('partials.checkbox', ['field' => 'terms', 'label' => '<a href="storage/' . \App\Term::orderBy('updated_at', 'desc')->first()->file . '">' . __('workspace.terms') . '</a>', 'required' => true])

                            @include('partials.submitfield', ['label' => __('document.submit')])
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection