routes/web.php
<?php

Route::get('/', function () {
    return view('index');
});

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

Auth::routes();

Route::middleware(['auth', 'workspace'])->group(function () {
    Route::resource('document/initialize', '\App\Http\Controllers\Document\InitializeController', ['only' => ['create', 'store']]);
    Route::resource('document/version', '\App\Http\Controllers\Document\VersionController', ['only' => ['edit', 'update']]);
    Route::resource('document/sign', '\App\Http\Controllers\Document\SignController', ['only' => ['index', 'edit', 'update']]);
    Route::resource('document/notification', '\App\Http\Controllers\Document\NotificationController', ['only' => ['index', 'edit', 'update']]);
    Route::resource('document', 'DocumentController');
    Route::resource('device', 'DeviceController');
    Route::resource('device/initialize', '\App\Http\Controllers\Device\InitializeController', ['as' => 'device', 'only' => ['create', 'store']]);
    Route::resource('workspace', 'WorkspaceController', ['only' => ['index', 'update']]);
});

app/Device.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Device extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'device';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['category_id', 'workspace_id', 'type', 'name', 'manufacturer', 'ce_mark', 'serial_number', 'year_of_construction', 'space', 'number', 'notes'];

    /********** Override **********/
    /**
     * Fill the model with an array of attributes.
     *
     * @param  array  $attributes
     * @return $this
     *
     * @throws \Illuminate\Database\Eloquent\MassAssignmentException
     */
    public function fill(array $attributes)
    {
        if (Auth::user()->workspace && !isset($attributes['workspace_id'])) {
            $attributes['workspace_id'] = Auth::user()->workspace->id;
        }
        return parent::fill($attributes);
    }
    /********** Override **********/

    /********** Voyager relations **********/
    /**
     * @return \Illuminate\Database\Eloquent\Relations\belongsTo
     */
    public function workspaceId()
    {
        return $this->belongsTo(\App\Workspace::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\belongsTo
     */
    public function categoryId()
    {
        return $this->belongsTo(\App\Category::class, 'category_id', 'id');
    }
    /********** Voyager relations **********/

    /********** Relations **********/
    /**
     * @return \Illuminate\Database\Eloquent\Relations\belongsTo
     */
    public function workspace()
    {
        return $this->workspaceId();
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\belongsTo
     */
    public function category()
    {
        return $this->categoryId();
    }
    /********** Relations **********/

    /********** Clone **********/
    public function clone() {
        $clone = $this->replicate();
        $clone->workspace_id = Auth::user()->workspace->id;
        $clone->save();

        return $clone;
    }
    /********** Clone **********/

    /********** Generator **********/
    public function getGeneratorAttribute($value = '') {
        return (new \App\Device($this));
    }
    /********** Generator **********/

}

app/Http/Controllers/Device/InitializeController.php
<?php

namespace App\Http\Controllers\Device;

use App\Workspace;
use Illuminate\Support\Facades\Auth;

class InitializeController
{
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Auth::user()->workspace->devices()->count()) {
            return redirect(route('device.index'));
        }

        $devices = Workspace::where('master', true)->first()->devices->map->clone();

        $devices->groupBy('category.id')->each(function ($devices, $category) {
            app(\App\Generator\Device::class)->create($devices, $category);
        });

        return redirect(route('device.index'));
    }
}

app/Http/Controllers/DeviceController.php
<?php

namespace App\Http\Controllers;

use App\Device;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class DeviceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $devices = Auth::user()->workspace->devices();

        if (!Auth::user()->workspace->master && Auth::user()->hasPermission('edit_documents') && !$devices->count()) {
            return redirect(route('device.initialize.create'));
        }

        if ($request->has('category')) {
            $devices = $devices->where('category_id', $request->category);
        }

        return view('device.index', ['devices' => $devices->paginate(config('document.pagination'))]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('device.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'type' => 'required|string|max:255',
            'name' => 'required|string|max:255',
            'manufacturer' => 'required|string|max:255',
        ]);

        $device = app(\App\Device::class)->fill($request->all());
        $device->save();

        app(\App\Generator\Device::class)->create(null, $device->category_id);

        return redirect(route('device.index', ['category' => $device->category_id]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Device $device
     * @return \Illuminate\Http\Response
     */
    public function edit(Device $device)
    {
        return view('device.edit')->withDevice($device);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Device $device
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Device $device)
    {
        $request->validate([
            'type' => 'required|string|max:255',
            'name' => 'required|string|max:255',
            'manufacturer' => 'required|string|max:255',
        ]);

        $device->fill($request->all());
        $device->save();

        app(\App\Generator\Device::class)->create(null, $device->category_id);

        return redirect(route('device.index', ['category' => $device->category_id]));
    }

}

resources/views/device/categories.blade.php
@if(!isset($categories))
    @php
        $categories = \App\Category::where('parent_id', null)->get();
        $class = 'list-group-root';
    @endphp
@endif

<div class="{{ $class }}" @if (isset($id)) id="item-{{ $id }}" @endif>
    @foreach($categories as $category)
        @if ($category->subCategories->count())
            @php
                $subCategory = in_array(request()->category, $category->subCategoriesIds());
            @endphp
            <span class="list-group-item @if ($category->id == request()->category) active @endif">
                <a href="#item-{{ $category->id }}" data-toggle="collapse" class="{{ $subCategory ? '' : 'collapsed' }}">
                    <i href="#item-{{ $category->id }}" class="glyphicon glyphicon-plus"></i>
                </a>
                <a href="{{ route('device.index', ['category' => $category->id]) }}" style="width: 90%;">
                    {{ $category->name }}
                </a>
                @include('device.categories', ['categories' => $category->subCategories, 'id' => $category->id, 'class' => 'collapse' . ($subCategory ? ' in' : '')])
            </span>
        @else
            <a href="{{ route('device.index', ['category' => $category->id]) }}" class="list-group-item @if ($category->id == request()->category) active @endif">
                {{ $category->name }}
            </a>
        @endif
    @endforeach
</div>

resources/views/device/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">{{ __('device.new_device') }}</div>
                    <div class="panel-body">
                        <form class="form-horizontal" method="POST" action="{{ route('device.store') }}" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            <input type="hidden" name="category_id" value="{{ request()->category }}">

                            @include('partials.textfield', ['field' => 'type', 'label' => __('device.type'), 'required' => true])
                            @include('partials.textfield', ['field' => 'name', 'label' => __('device.name'), 'required' => true])
                            @include('partials.textfield', ['field' => 'manufacturer', 'label' => __('device.manufacturer'), 'required' => true])
                            @include('partials.textfield', ['field' => 'ce_mark', 'label' => __('device.ce_mark'), 'required' => false])
                            @include('partials.textfield', ['field' => 'serial_number', 'label' => __('device.serial_number'), 'required' => false])
                            @include('partials.textfield', ['field' => 'year_of_construction', 'label' => __('device.year_of_construction'), 'required' => false])
                            @include('partials.textfield', ['field' => 'space', 'label' => __('device.space'), 'required' => false])
                            @include('partials.textfield', ['field' => 'number', 'label' => __('device.number'), 'required' => false])

                            @include('partials.submitfield', ['label' => __('document.submit')])
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/device/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">{{ __('device.edit_device', ['category' => $device->category->name]) }}</div>
                    <div class="panel-body">
                        <form class="form-horizontal" method="POST" action="{{ route('device.update', $device->id) }}" enctype="multipart/form-data">
                            {{ method_field('put') }}
                            {{ csrf_field() }}

                            @include('partials.textfield', ['field' => 'type', 'label' => __('device.type'), 'value' => $device->type, 'required' => true])
                            @include('partials.textfield', ['field' => 'name', 'label' => __('device.name'), 'value' => $device->name, 'required' => true])
                            @include('partials.textfield', ['field' => 'manufacturer', 'label' => __('device.manufacturer'), 'value' => $device->manufacturer, 'required' => true])
                            @include('partials.textfield', ['field' => 'ce_mark', 'label' => __('device.ce_mark'), 'value' => $device->ce_mark, 'required' => false])
                            @include('partials.textfield', ['field' => 'serial_number', 'label' => __('device.serial_number'), 'value' => $device->serial_number, 'required' => false])
                            @include('partials.textfield', ['field' => 'year_of_construction', 'label' => __('device.year_of_construction'), 'value' => $device->year_of_construction, 'required' => false])
                            @include('partials.textfield', ['field' => 'space', 'label' => __('device.space'), 'value' => $device->space, 'required' => false])
                            @include('partials.textfield', ['field' => 'number', 'label' => __('device.number'), 'value' => $device->number, 'required' => false])

                            @include('partials.submitfield', ['label' => __('document.submit')])
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/device/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-4">
            @if (request()->route()->named('device.index'))
                <div class="panel panel-default">
                    <div class="panel-heading">{{ __('document.categories') }}</div>
                    <div class="panel-body">
                        @include('device.categories')
                    </div>
                </div>
            @endif
        </div>
        <div class="col-md-8">
            <div class="panel panel-default">
                <div class="panel-heading">{{ __('device.device') }}</div>
                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    @if (request()->category && Auth::user()->hasPermission('edit_documents'))
                        <div class="btn-group">
                            <a href="{{ route('device.create', ['type' => \App\Generator\Html::class, 'category' => request()->category]) }}" class="btn btn-default">{{ __('device.new') }}</a>
                        </div>
                        <hr>
                    @endif

                    @if ($devices->count())
                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <td>{{ __('device.type') }}</td>
                                        <td>{{ __('device.name') }}</td>
                                        <td>{{ __('device.number') }}</td>
                                        @if(Auth::user()->hasPermission('edit_documents'))
                                            <td></td>
                                        @endif
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($devices as $device)
                                        <tr>
                                            <td>{{ $device->type }}</td>
                                            <td>{{ $device->name }}</td>
                                            <td>{{ $device->number }}</td>
                                            @if(Auth::user()->hasPermission('edit_documents'))
                                                <td align="center" style="font-size: 2rem;">
                                                    <a href="{{ route('device.edit', $device->id) }}">
                                                        <span class="fa fa-edit"></span>
                                                    </a>
                                                </td>
                                            @endif
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        {{ $devices->appends(request()->input())->links() }}
                    @else
                        <p>{{ __('device.no_devices_category') }}</p>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection